Folder-Structure
chingu-voyages/v39-bears-team-16 pull request #37
Opened 2022-04-27 03:42 UTC by Danneytrieu

I made a few changes and tried to establish a decent way to organize everything. Certain practices won't make much sense now but as the projects grow, they will come in handy as we try to navigate and change contents/styles/themes. Here is my approach:

- theme.js -> each theme will hold 2 obj, `color` can be used to apply to text, while `background` applies to container, card or button. Also used theme provider to access these objects globally. Yes, some colors do repeat but the color collection might change in the future and it will be easier to adopt more themes later. 
- global-style.tsx ->  added a few reusable template component 
- SignUp.elements.tsx -> hold all related styled components and styled icon that belong to SignUp 
- SignUp.tsx -> import everything from SignUp.elements.tsx and applied separately to prevent future error prone. 

Please let me know if something doesn't make sense or better way to structure and better practices.

2022-04-27 14:38 UTC, theodorusandi requested changes
I think the two global components (Container and Card) should not be inside global style since its only for styling and we don't want to import all from global. Would be better to put it just under components folder as two independent files.

2022-04-27 15:25 UTC, jpatrici reviewed
I think for the common components that can be used widely, we should still put it under `components` folder. So things like `Container`, `Section` can be put under `common` folder. Same thing with the `Auth` as from my comment, they can be put under `components`.

Maybe we can follow this https://github.com/withspectrum/spectrum/tree/alpha/src, so all the components are inside `components` folder. Pages are inside `views` folder, and they import the common components from `components` folder. Any specific styling just for the page, can go inside that page folder. For example
```
/components
   Container.tsx
   Section.tsx
   Auth.tsx
/pages
   /SignUp
      SignUp.tsx
      SignUp.styled.tsx
   /SignIn
      SignIn.tsx
```
I also agree with @theodorusandi that they shouldn't be in the global style file, and to avoid doing `import *`

2022-04-27 20:36 UTC, Danneytrieu commented on src/components/SignUp/SignUp.elements.tsx
> +`;
interesting! I was looking for something like this

2022-04-27 20:36 UTC, Danneytrieu commented on src/components/SignUp/SignUp.elements.tsx
> +import * as global from '../../global-style';
gotcha

2022-04-27 23:16 UTC, RDiMag approved these changes

2022-04-28 00:21 UTC, theodorusandi approved these changes
Looks good to me

2022-04-28 00:27 UTC, jpatrici approved these changes
thanks Danney!

2022-04-28 21:38 UTC, merged