created forgot password page
chingu-voyages/v39-bears-team-16 pull request #45
Opened 2022-05-04 01:38 UTC by Danneytrieu

2022-05-04 18:19 UTC, theodorusandi requested changes
Danney could you add email field for reset password page? I follow Laravel's convention in resetting password. Other pages look awesome, thank you!
![](https://cdn.discordapp.com/attachments/964171102924443669/969998203669852181/reset_password.png)

2022-05-04 23:19 UTC, RDiMag approved these changes

2022-05-05 00:46 UTC, Danneytrieu commented
> Danney could you add email field for reset password page? I follow Laravel's convention in resetting password. Other pages look awesome, thank you! ![](https://camo.githubusercontent.com/10c026c7eacc3d7f5b12573bf0ddb72660648e0532f4cb2fd1cfb9d85b75aef5/68747470733a2f2f63646e2e646973636f72646170702e636f6d2f6174746163686d656e74732f3936343137313130323932343434333636392f3936393939383230333636393835323138312f72657365745f70617373776f72642e706e67)

it's good to go buddy. thank you

2022-05-05 01:30 UTC, jpatrici approved these changes

2022-05-05 01:30 UTC, theodorusandi approved these changes
thanks!

2022-05-05 02:08 UTC, merged